### ISSUE TITLE
Delete CouchDB Session?

### ISSUE THREAD

**Issue by klaemo** [ubilabs/hapi-auth-couchdb-cookie#4]
Hey there :)

Shouldn't `request.auth.session.clear()` also [delete the session](http://docs.couchdb.org/en/latest/api/server/authn.html#delete--_session) on CouchDB?

**Comment by KlausTrainer** [comment]
Hey!

CouchDB doesn't really have the notion of a session in the sense that there's any state. It only checks the validity of the `AuthSession` cookie (see https://github.com/apache/couchdb/blob/1.6.1/src/couchdb/couch_httpd_auth.erl#L162). The point of the `DELETE /_session` endpoint is just that CouchDB will return the `Set-Cookie: AuthSession=; Version=1; Path=/; HttpOnly` header, which tells the browser to clear the `AuthSession` cookie value. That's why it shouldn't be necessary here to send that request.

**Comment by klaemo** [comment]
Got it, thank you :)
